[project]
name = "kabs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imageio>=2.37.2",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "meshio>=5.3.5",
    "nest-asyncio2>=1.7.2",
    "numpy>=2.4.2",
    "pyevtk>=1.6.0",
    "pyvista>=0.47.1",
    "taichi>=1.7.4",
    "trame>=3.12.0",
    "trame-vtk>=2.11.3",
    "trame-vuetify>=3.2.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.0",
    "ruff>=0.15.6",
]
