[project]
name = "kabs"
version = "0.0.1-dev15"
description = "A tool for finding the absolute permeability from a volumetric image using the lattice Boltzmann method"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imageio>=2.37.2",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "meshio>=5.3.5",
    "nest-asyncio2>=1.7.2",
    "numpy>=2.4.2",
    "pyevtk>=1.6.0",
    "pyvista>=0.47.1",
    "taichi>=1.7.4",
    "trame>=3.12.0",
    "trame-vtk>=2.11.3",
    "trame-vuetify>=3.2.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.0",
    "pytest-cov>=7.1.0",
    "ruff>=0.15.6",
]

[tool.bumpversion]
current_version = "0.0.1-dev15"
parse = """(?x)
    (?P<major>0|[1-9]\\d*)\\.
    (?P<minor>0|[1-9]\\d*)\\.
    (?P<patch>0|[1-9]\\d*)
    (?:
        -                             # dash separator for pre-release section
        (?P<pre_l>[a-zA-Z-]+)         # pre-release label
        (?P<pre_n>0|[1-9]\\d*)        # pre-release version number
    )?                                # pre-release section is optional
"""
serialize = [
    "{major}.{minor}.{patch}-{pre_l}{pre_n}",
    "{major}.{minor}.{patch}",
]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
tag = true
sign_tags = false
tag_name = "v{new_major}.{new_minor}.{new_patch}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "maint: bump version: {current_version} → {new_version} [skip bump]"
commit_args = ""

[tool.bumpversion.parts.pre_l]
values = ["dev"]
optional_value = "dev"

[tool.coverage.run]
source = ["kabs"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "@ti\\.kernel",
    "@ti\\.func",
]

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = 'version = "{current_version}"'
replace = 'version = "{new_version}"'
